# Generated by Django 2.1.2 on 2018-12-06 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('Folio', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Cliente', models.CharField(max_length=40, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_termino', models.DateTimeField(blank=True, null=True)),
                ('Id_ascensor', models.IntegerField(blank=True, max_length=4, null=True)),
                ('modelo_ascensor', models.CharField(blank=True, max_length=200, null=True)),
                ('fallas', models.CharField(max_length=200)),
                ('piezas_cambiadas', models.CharField(max_length=200)),
                ('Nombre_Tecnico', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Completo', models.CharField(blank=True, max_length=200, null=True)),
                ('Direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('Ciudad', models.CharField(blank=True, max_length=200, null=True)),
                ('Comuna', models.CharField(blank=True, max_length=200, null=True)),
                ('Correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
