# Generated by Django 2.1.2 on 2018-12-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='Id_ascensor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
