# Generated by Django 2.1.2 on 2018-12-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ascensor', '0002_auto_20181206_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocliente',
            name='author',
        ),
    ]
