# Generated by Django 2.1.2 on 2018-12-09 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ascensor', '0005_auto_20181209_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='author',
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='Nombre_Tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
