# Generated by Django 2.1.2 on 2018-12-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascensor', '0006_auto_20181209_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='hora_termino',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
