# Generated by Django 2.1.2 on 2018-12-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascensor', '0007_auto_20181209_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fallas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='piezas_cambiadas',
            field=models.TextField(),
        ),
    ]
