# Generated by Django 2.1.2 on 2018-12-10 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ascensor', '0008_auto_20181209_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocliente',
            name='Tecnico_Asociado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
